# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Perform SSW alignment on a pre-computed similarity matrix
#'
#' @param sim_matrix Numeric matrix (n x m) of pairwise similarities
#' @param gap_open Gap opening penalty (negative)
#' @param gap_extend Gap extension penalty (negative)
#' @return List with score, align1 (1-indexed, 0=gap), align2 (1-indexed, 0=gap)
#' @keywords internal
c_ssw_align <- function(sim_matrix, gap_open, gap_extend) {
    .Call(`_semanticsmith_c_ssw_align`, sim_matrix, gap_open, gap_extend)
}

